use eldenring;

-- Tabella Categoria
INSERT INTO Categorie (id_categoria, nome)
VALUES ('DAG', 'Pugnale'),
       ('LML', 'Lama da lancio'),
       ('SPD', 'Spada dritta'),
       ('SPD_L', 'Spadone leggero'),
       ('SPD_GR', 'Spadone'),
       ('SPD_CL', 'Spadone colossale'),
       ('SPD_PF', 'Spada perforante'),
       ('SPD_PF_P', 'Spada perforante pesante'),
       ('SPD_C', 'Spada curva'),
       ('SPD_GR_C', 'Spadone curvo'),
       ('LMR', 'Lama rovesciata'),
       ('KAT', 'Katana'),
       ('KAT_GR', 'Katana gigante'),
       ('LMG', 'Lama gemella'),
       ('ASC', 'Ascia'),
       ('ASC_GR', 'Ascia pesante'),
       ('MRT', 'Martello'),
       ('MRT_GR', 'Martello da guerra'),
       ('FLG', 'Flagello'),
       ('ARM_C', 'Arma colossale'),
       ('LNC', 'Lancia'),
       ('LNC_GR', 'Lancia pesante'),
       ('ALB', 'Alabarda'),
       ('FLC', 'Falce'),
       ('FRS', 'Frusta'),
       ('PUG', 'Pugno'),
       ('COR_COR', 'Corpo a corpo'),
       ('ART', 'Artiglo'),
       ('ART_F', 'Artigli ferino'),
       ('BTP', 'Bottiglia di profumo'),
       ('ARC_L', 'Arco leggero'),
       ('ARC', 'Arco'),
       ('ARC_GR', 'Arco pesante'),
       ('BLS', 'Balestra'),
       ('BLS_GR', 'Balista'),
       ('BST_GL', 'Bastone di scintipietra'),
       ('SG_S', 'Sigillo sacro'),
       ('TRC', 'Torcia'),
       ('SCD_P', 'Scudo piccolo'),
       ('SCD_M', 'Scudo medio'),
       ('SCD_GR', 'Scudo pesante'),
       ('SCD_AF', 'Scudo da affondo'),
       ('FRC', 'Freccia'),
       ('FRC_GR', 'Freccia pesante'),
       ('DRD', 'Dardo'),
       ('DRD_GR', 'Dardo pesante');
