use eldenring;

-- Tabella Armi
insert into armi (nome, descrizione, immagine, id_categoria, peso, ottenimento)
values ("FIRE KNIGHT'S SHORTSWORD",
        "Shortsword used by the Fire Knights. A slender blade that undulates like fire. Blessed with a flame incantation. Further flame imbuement will amplify the effect and greatly increase the armament's power.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/fire_knights_shortsword_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
        "DAG", 2.0,
        "Ha una probabilità del 4,0% di cadere dai Cavalieri di Fuoco che brandiscono questa arma in Shadow Keep. Può essere ottenuto farmando, uccidendo il Cavaliere di Fuoco sotto il deposito, nel sito di Grazia del Loft, e il Cavaliere di Fuoco appena a est del deposito, nel sito di Grazia del Settimo Piano."),
       ("MAIN-GAUCHE",
        "Dagger with a large hand guard. Intended to be used in the left hand, thereby complementing a piercing sword or identical blade held in the right to enable a distinctive style of fighting.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/main-gauche_dagger_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
        "DAG", 2.0,
        "Shadow Keep: Dai punti di grazia della Main Gate Plaza, vai verso ovest e sali le scale fino a quando il soldato ti tenderà un'imboscata. Poi entra in quella stanza e sulla destra c'è un'altra porta. L'oggetto si trova lì, protetto da due soldati e un Blacksteel Knight."),
       ("DAGGER",
        "A standard dagger with a straight blade. Though modest in reach and capacity for harm, this weapon is light enough to jab in rapid succession and delivers devastating critical hits.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/dagger_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Può essere acquistato dai Twin Maiden Husks al Roundtable Hold per una somma di 18.400 Runes. Può essere ottenuto anche come bottino dai Highwaymen e da diversi tipi di Foot Soldiers. Numerosi soldati possono essere incontrati nelle fasi iniziali del gioco nel campo a est della Warmaster's Shack. Ha una probabilità del 4.00% di essere lasciato dal Messmer Foot Soldier."),
       ("PARRYNG DAGGER",
        "A knife with curved handguards. Designed to parry, turning foes' attacks against them. For master of combat who anticipate every enemy strike and counter accordingly, this weapon is all they need.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/parrying_dagger_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Venduto da Patches nella Grotta dell’Acquafosca per 1600 Rune dopo che ha allestito il negozio. Può essere acquistato dalle Gemelle Vergini presso la Tavola Rotonda consegnando loro il Campanello di Patches."),
       ("MISÈRICORDE",
        "Dagger favored by military physicians in white. The pointed blade is hard and sharp, making critical hits especially potent. Medicine is mercy. and mercy upon the battlefield is ruthless. Beware the killers clothed as men of compassion.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/misericorde_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Posizione: Castello Grantempesta. Può essere saccheggiato da un cadavere che si trova nella grande sala delle armerie, vicino alla fortezza dello Scion Innestato. Sarà necessario utilizzare la Chiave della Spadaspietra sulla statua dell'imp per dissipare la nebbia bianca che blocca l'ingresso."),
       ("GREAT KNIFE",
        "Large knife with a broad, curved blade. This weapon is designed to slash and rend, inflicting blood loss upon the recipient.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/great_knife_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Equipaggiamento iniziale per la classe Bandito. Drop raro da Demi-Umani che brandiscono questa arma. Capanna del Fabbro: quattro Demi-Umani nascosti in un gregge di pecore a nord del Sito di Grazia. Caverna di Cristallo in riva al lago: un Demi-Umano nascosto in un cespuglio all'inizio del dungeon. Caverna del Vulcano: può essere ottenuto da due Demi-Umani appena fuori dalla caverna."),
       ("BLOODSTAINED DAGGER",
        "Dagger with a bloodstained blade. Afflicts targets with blood loss. As blood darkened the dagger through repeated slashing and stabbing, its blade only grew sharper and harder.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/bloodstained_dagger_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Drop raro dai Capo Demi-Umani. C'è un Capo Demi-Umano che dorme prima del ponte di legno che porta all'Albero Minore nell'Area della Penisola Piangente. Ce ne sono 2 vicini tra loro nel Villaggio degli Eremiti. Un modo veloce per fare farming è andare alla Grazia del Mago Primordiale Azur, seguire il muro andando verso sud e troverai uno di loro isolato. Uccidilo e ce ne sarà uno subito di fianco, lontano dal muro. Ombra dell'Albero Sacro - Costa Cerulea: uno si trova in una caverna vicino a questo Frammento dell'Albero Scaduto. L'altro può essere trovato a proteggere questo Boss di Campo."),
       ("ERDSTEEL DAGGER",
        "An erdsteel dagger with a grass crest engraved upon its blade. Carried by the Erdtree royalty for self-defense in times of peace. Though forged to a high standard, the weapon is difficult to wield. Attack power also scales with faith.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdsteel_dagger_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Dato da Kenneth Haight come ricompensa per aver ripulito Forte Haight. Si trova a nord-ovest del balcone dell'Avenue a Leyndell, Capitale Reale. Scendi in una fossa con una Statua Rovinata e lo troverai su un cadavere."),
       ("WAKIZASHI",
        "Short sword with a tempering pattern on the blade. A weapon unique to warriors of the Land of Reeds. Afflicts targets with blood loss. These swords are considered auxiliary weapons. Yet, one man is known to wield this weapon in his left hand while using a full-sized katana in his right. A demonic swordsman known only as Okina.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/wakizashi_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 3.0,
        "All'interno della Grotta di Gaol, si trova in una delle celle chiuse. Il giocatore deve prima sbloccare le celle."),
       ("CELEBRANT'S SICKLE",
        "Sickle decorated with flowers and many-coloured fabrics. Ceremonial tool used by dancers during the festivities of Dominula. Its attacks can slip through an enemy's guard. Crafted from human bone. Grants trace amounts of runes on landing attacks.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/celebrants-sickle_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Drop raro dai Celebranti che la brandiscono nel Villaggio del Mulino a Vento. Questi nemici sono facilmente riconoscibili dai loro mantelli blu. Due si trovano nel grande gruppo a metà strada tra il Villaggio del Mulino a Vento e i Siti di Grazia delle Alture del Mulino a Vento. Questi nemici sono passivi finché non vengono provocati e, oltre all'arma, hanno la possibilità di lasciare Cadaveri d’Ossa Umana e Rune Dorate [3], rendendo il farming semplice e redditizio. Questo gruppo include anche due Celebranti che possono lasciare il Rastrello Celebrativo."),
       ("IVORY SICKLE",
        "Sickle fashioned from ivory. Weapon carried by aged Albunaurics. These weapons are evidence of their dedication to the Haligtree, despite never having entered its presence.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ivory_sickle_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Si trova nel Villaggio degli Albinauri. È su una piccola collina oltre la Grazia, in una bara di pietra."),
       ("CRYSTAL KNIFE",
        "A knife made by sharpening hard crystal. Signature weapon of glintstone miners. Used as a tool to extract glintstone from broken rock, and as such a faint magic enwreathes the blade.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/crystal_knife_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Si trova in un forziere all'interno del Tunnel di Cristallo di Raya Lucaria, in un'area di stoccaggio tre livelli più in basso, sorvegliata da Marionette."),
       ("SCORPION STINGER",
        "Dagger fashioned from a great scorpion's tail, glistening with scarlet rot. A ceremonial tool used by heretics, crafted from the relic of a sealed outer god.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/scorpions_stinger_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.5,
        "Si trova nel Lago della Putrefazione. Attraversa la palude e passa attraverso l'ingresso con grandi statue su entrambi i lati per raggiungere il Sito di Grazia del Gran Chiostro. Usa le sporgenze per scendere fino in fondo e procedi dritto (verso ovest): troverai il pugnale in un forziere."),
       ("CINQUEDEA",
        "Short sword given to high ranking clergymen of Farum Azula. Raises potency of bestial incantations. The design celebrates a beast's five fingers, symbolic of the intelligence once granted upon their kind.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/cinquedea_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 3.5,
        "Posizione: La Cinquedea si trova alla base della struttura esterna del Santuario Bestiale, vicino a una statua di ratto spezzata. Per raggiungere questo punto, vai alla scogliera ovest fuori dal santuario e scendi seguendo una serie di radici e piattaforme. Salta su un ramo sporgente e continua a scendere utilizzando le sporgenze e i pilastri. Puoi usare le Pietre Arcobaleno per capire dove cadere successivamente. Una volta raggiunto il livello più basso, esplorando quest'area otterrai questo pugnale e anche il Talismano dello Scudo Crestato di Drago."),
       ("GLINTSTONE KRIS",
        "Ritual blade once presented to Leyndell by the Academy of Raya Lucaria to celebrate their newfound peace. Though the weapon is embedded with precious glintstones and features Erdtree ornamentation, the undulating blade is symbolic of an ancient ritual.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/glintstone_kris_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Ricompensa per i giocatori che avanzano nella linea di missioni della Strega Sellen e si schierano dalla sua parte."),
       ("REDUVIA",
        "Jagged dagger with a distinctive curled blade. Carried by the noble servants of the Lord of Blood. This dagger rips the flesh as it enters, inflicting blood loss with sickening efficacy. A proud testament to the success of its vicious design, this weapon is perpetually coated in blood.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/reduvia_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.5, "Lasciato cadere da Dito Insanguinato Nerijus."),
       ("BLADE OF CALLING",
        "Dagger given to one who set out on a journey to fulfill her duty long ago. The power of its former owner, the kindling maiden, is still apparent. The one who walks alongside flame, Shall one day meet the road of Destined Death.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/blade_of_calling_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 1.5,
        "Dal Sito di Grazia delle Terre Proibite, torna indietro e dirigiti verso l'ascensore. Fai attenzione verso ovest-sudovest, quindi attiva l'ascensore e cerca un'apertura in cui saltare. La Lama della Chiamata è sul tavolo nella stanza alla fine di questo corridoio."),
       ("BLACK KNIFE",
        "Dagger once belonging to one of the assassins who murdered Godwyn the Golden on the Night of the Black Knives. A ritual performed on the oddly misshapen blade imbued it with the power of the stolen Rune of Death.",
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/black_knife_dagger_weapon_elden_ring_wiki_guide_200px.png",
        "DAG", 2.0,
        "Questo è un drop ottenuto sconfiggendo l'Assassino della Lama Nera all'ingresso della Tomba dell'Eroe Santo, nell'Altopiano di Altus. Questo boss si trova direttamente a ovest del Sito di Grazia del Sentiero delle Mura.");

-- Tabella Scaling
insert into scaling (id_arma, id_attributo, grado_scaling, parametro)
values (1, "FOR", "D", 8),   -- Fire Knight'S Shortsword
       (1, "DES", "D", 13),
       (1, "FED", "D", 12),
       (2, "FOR", "D", 7),   -- Main-gauche
       (2, "DES", "C", 15),
       (3, "FOR", "D", 5),   -- Dagger
       (3, "DES", "C", 9),
       (4, "FOR", "E", 5),   -- Parryng Dagger
       (4, "DES", "C", 14),
       (5, "FOR", "E", 7),   -- Misèricorde
       (5, "DES", "D", 12),
       (6, "FOR", "E", 6),   -- Great Knife
       (6, "DES", "D", 12),
       (7, "FOR", "C", 9),   -- Bloodstained Dagger
       (7, "DES", "E", 12),
       (8, "FOR", "D", 7),   -- Erdsteel
       (8, "DES", "D", 12),
       (8, "FED", "D", 14),
       (9, "FOR", "D", 9),   -- Wakizashi
       (9, "DES", "D", 13),
       (10, "FOR", "E", 6),  -- Celebran's Sickle
       (10, "DES", "C", 11),
       (11, "FOR", "E", 6),  -- Ivory Sickle
       (11, "DES", "D", 11),
       (11, "INT", "D", 13),
       (12, "FOR", "D", 8),  -- Crystal Knife
       (12, "DES", "D", 12),
       (12, "INT", "D", 7),
       (13, "FOR", "D", 7),  -- Scorpion'S Stinger
       (13, "DES", "C", 12),
       (14, "FOR", "D", 10), -- Cinquedea
       (14, "DES", "E", 10),
       (15, "FOR", "E", 5),  -- Glintstone Kris
       (15, "DES", "D", 12),
       (15, "INT", "D", 16),
       (16, "FOR", "E", 5),  -- Reduvia
       (16, "DES", "D", 13),
       (16, "ARC", "D", 13),
       (17, "FOR", "D", 6),  -- Blade Of Calling
       (17, "DES", "D", 13),
       (17, "FED", "C", 15),
       (18, "FOR", "E", 8),  -- Black Knife
       (18, "DES", "D", 12),
       (18, "FED", "D", 18);

-- Tabella Statistiche
insert into statistiche (id_arma, id_tipo, valore, tipologia)
values (1, "FIS", 75, 'ATT'),  -- Fire Knight's Shortsword
       (1, "FUO", 22, 'ATT'),
       (1, "CRT", 110, 'ATT'),
       (1, "FIS", 32, "DEF"),
       (1, "MAG", 18, "DEF"),
       (1, "FUO", 31, "DEF"),
       (1, "FUL", 18, "DEF"),
       (1, "SAC", 18, "DEF"),
       (1, "BST", 15, "DEF"),
       (2, "FIS", 79, "ATT"),  -- Main-gauche
       (2, "CRT", 110, "ATT"),
       (2, "FIS", 38, "DEF"),
       (2, "MAG", 22, "DEF"),
       (2, "FUO", 22, "DEF"),
       (2, "FUL", 22, "DEF"),
       (2, "SAC", 22, "DEF"),
       (2, "BST", 16, "DEF"),
       (3, "FIS", 74, "ATT"),  -- Dagger
       (3, "CRT", 130, "ATT"),
       (3, "FIS", 35, "DEF"),
       (3, "MAG", 20, "DEF"),
       (3, "FUO", 20, "DEF"),
       (3, "FUL", 20, "DEF"),
       (3, "SAC", 20, "DEF"),
       (3, "BST", 15, "DEF"),
       (4, "FIS", 75, "ATT"),  -- Parrying Dagger
       (4, "CRT", 110, "ATT"),
       (4, "FIS", 35, "DEF"),
       (4, "MAG", 20, "DEF"),
       (4, "FUO", 20, "DEF"),
       (4, "FUL", 20, "DEF"),
       (4, "SAC", 20, "DEF"),
       (4, "BST", 15, "DEF"),
       (5, "FIS", 92, "ATT"),  -- Miséricorde
       (5, "CRT", 92, "ATT"),
       (5, "FIS", 36, "DEF"),
       (5, "MAG", 21, "DEF"),
       (5, "FUO", 21, "DEF"),
       (5, "FUL", 21, "DEF"),
       (5, "SAC", 21, "DEF"),
       (5, "BST", 15, "DEF"),
       (6, "FIS", 75, "ATT"),  -- Great Knife
       (6, "CRT", 110, "ATT"),
       (6, "FIS", 35, "DEF"),
       (6, "MAG", 20, "DEF"),
       (6, "FUO", 20, "DEF"),
       (6, "FUL", 20, "DEF"),
       (6, "SAC", 20, "DEF"),
       (6, "BST", 15, "DEF"),
       (7, "FIS", 81, "ATT"),  -- Bloodstained Dagger
       (7, "CRT", 110, "ATT"),
       (7, "FIS", 36, "DEF"),
       (7, "MAG", 21, "DEF"),
       (7, "FUO", 21, "DEF"),
       (7, "FUL", 21, "DEF"),
       (7, "SAC", 21, "DEF"),
       (7, "BST", 15, "DEF"),
       (8, "FIS", 67, "ATT"),  -- Erdsteel Dagger
       (8, "CRT", 110, "ATT"),
       (8, "FIS", 36, "DEF"),
       (8, "MAG", 21, "DEF"),
       (8, "FUO", 21, "DEF"),
       (8, "FUL", 21, "DEF"),
       (8, "SAC", 21, "DEF"),
       (8, "BST", 15, "DEF"),
       (9, "FIS", 94, "ATT"),  -- Wakizashi
       (9, "CRT", 100, "ATT"),
       (9, "FIS", 42, "DEF"),
       (9, "MAG", 24, "DEF"),
       (9, "FUO", 24, "DEF"),
       (9, "FUL", 24, "DEF"),
       (9, "SAC", 24, "DEF"),
       (9, "BST", 18, "DEF"),
       (10, "FIS", 79, "ATT"), -- Celebrant's Sickle
       (10, "CRT", 100, "ATT"),
       (10, "FIS", 35, "DEF"),
       (10, "MAG", 20, "DEF"),
       (10, "FUO", 20, "DEF"),
       (10, "FUL", 20, "DEF"),
       (10, "SAC", 20, "DEF"),
       (10, "BST", 15, "DEF"),
       (11, "FIS", 60, "ATT"), -- Ivory Sickle
       (11, "MAG", 60, "ATT"),
       (11, "CRT", 100, "ATT"),
       (11, "FIS", 26, "DEF"),
       (11, "MAG", 42, "DEF"),
       (11, "FUO", 15, "DEF"),
       (11, "FUL", 15, "DEF"),
       (11, "SAC", 15, "DEF"),
       (11, "BST", 15, "DEF"),
       (12, "FIS", 82, "ATT"), -- Crystal Knife
       (12, "MAG", 53, "ATT"),
       (12, "CRT", 100, "ATT"),
       (12, "FIS", 32, "DEF"),
       (12, "MAG", 31, "DEF"),
       (12, "FUO", 18, "DEF"),
       (12, "FUL", 18, "DEF"),
       (12, "SAC", 18, "DEF"),
       (12, "BST", 15, "DEF"),
       (13, "FIS", 79, "ATT"), -- Scorpion's Stinger
       (13, "CRT", 110, "ATT"),
       (13, "FIS", 38, "DEF"),
       (13, "MAG", 22, "DEF"),
       (13, "FUO", 22, "DEF"),
       (13, "FUL", 22, "DEF"),
       (13, "SAC", 22, "DEF"),
       (13, "BST", 16, "DEF"),
       (14, "FIS", 98, "ATT"), -- Cinquedea
       (14, "CRT", 100, "ATT"),
       (14, "FIS", 43, "DEF"),
       (14, "MAG", 25, "DEF"),
       (14, "FUO", 25, "DEF"),
       (14, "FUL", 25, "DEF"),
       (14, "SAC", 25, "DEF"),
       (14, "BST", 16, "DEF"),
       (15, "FIS", 57, "ATT"), -- Glinstone Kris
       (15, "MAG", 68, "ATT"),
       (15, "CRT", 110, "ATT"),
       (15, "FIS", 23, "DEF"),
       (15, "MAG", 45, "DEF"),
       (15, "FUO", 14, "DEF"),
       (15, "FUL", 14, "DEF"),
       (15, "SAC", 14, "DEF"),
       (15, "BST", 15, "DEF"),
       (16, "FIS", 79, "ATT"), -- Reduvia
       (16, "CRT", 110, "ATT"),
       (16, "FIS", 38, "DEF"),
       (16, "MAG", 22, "DEF"),
       (16, "FUO", 22, "DEF"),
       (16, "FUL", 22, "DEF"),
       (16, "SAC", 22, "DEF"),
       (16, "BST", 16, "DEF"),
       (17, "FIS", 71, "ATT"), -- Blade Of Calling
       (17, "SAC", 43, "ATT"),
       (17, "CRT", 110, "ATT"),
       (17, "FIS", 31, "DEF"),
       (17, "MAG", 18, "DEF"),
       (17, "FUO", 18, "DEF"),
       (17, "FUL", 18, "DEF"),
       (17, "SAC", 30, "DEF"),
       (17, "BST", 15, "DEF"),
       (18, "FIS", 66, "ATT"), -- Black Knife
       (18, "SAC", 65, "ATT"),
       (18, "CRT", 110, "ATT"),
       (18, "FIS", 26, "DEF"),
       (18, "MAG", 15, "DEF"),
       (18, "FUO", 15, "DEF"),
       (18, "FUL", 15, "DEF"),
       (18, "SAC", 42, "DEF"),
       (18, "BST", 15, "DEF");

-- Tabella ArmiEffetto
insert into ArmiEffetti (id_arma, nome_effetto, valore)
values (6, "Sanguinamento", 38), -- GREAT KNIFE
       (7, "Sanguinamento", 38), -- BLOODSTAINED DAGGER
       (9, "Sanguinamento", 38), -- WAKIZASHI
       (13, "Marcescenza", 50),  -- SCORPION STINGER
       (16, "Sanguinamento", 50); -- REDUVIA
